Add cli
borschik/borschik-hash pull request #1
Opened 2017-03-09 15:11 UTC by Yeti-or

2017-03-09 17:20 UTC, blond requested changes

2017-03-09 17:20 UTC, blond commented on package.json
> +    "meow": "^3.7.0"
нужна точная зависимость

2017-03-09 17:20 UTC, blond commented on bin/cli.js
> +cli.input.forEach(file => console.log(bHash(file)));
Тут имя файла?

Тогда надо ещё прочитать файл.

2017-03-09 17:20 UTC, blond commented on bin/cli.js
> +const bHash = require('..');
`bHash` -> `borschikHash`

2017-03-09 17:20 UTC, blond commented on bin/cli.js
> +const meow = require('meow');
У нас тут поддержка 0.10 )

2017-03-09 17:20 UTC, blond commented on bin/cli.js
> +const meow = require('meow');
отказываться не очень хочется :(

2017-03-09 17:21 UTC, blond reviewed
Нужно добавить в readme про CLI

2017-03-09 17:31 UTC, Yeti-or commented on bin/cli.js
> +cli.input.forEach(file => console.log(bHash(file)));
бля как я тупанул то =))

2017-03-10 01:19 UTC, Yeti-or commented
@blond  🆙 
tested on `0.9.12`

2017-03-10 04:58 UTC, blond approved these changes

2017-03-10 04:59 UTC, merged